// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	dto "github.com/kingrain94/audit-log-api/internal/api/dto"
	mock "github.com/stretchr/testify/mock"
)

// WebSocketBroadcaster is an autogenerated mock type for the WebSocketBroadcaster type
type WebSocketBroadcaster struct {
	mock.Mock
}

// BroadcastLog provides a mock function with given fields: log
func (_m *WebSocketBroadcaster) BroadcastLog(log *dto.AuditLogResponse) {
	_m.Called(log)
}

// NewWebSocketBroadcaster creates a new instance of WebSocketBroadcaster. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebSocketBroadcaster(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebSocketBroadcaster {
	mock := &WebSocketBroadcaster{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
